apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  labels:
    strimzi.io/cluster: kafka-common
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
