apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: common-postgres
  namespace: postgres
spec:
  teamId: "common"
  volume:
    storageClass: yc-network-hdd
    size: 5Gi
  numberOfInstances: 2
  users:
    xbot.su:
    - superuser
    - createdb
    - login
  databases:
    xbot: xbot.su
  postgresql:
    version: "14"
